
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int FUNC_COUNTDISTINCT = 32;
  public static final int DECL_IF = 23;
  public static final int OUTPUT = 26;
  public static final int CERRAR_BLOQUE = 38;
  public static final int OP_NOT = 15;
  public static final int CTE_STRING = 6;
  public static final int OP_AND = 13;
  public static final int COND_IGUAL = 16;
  public static final int CL_WHILE = 22;
  public static final int CERRAR_PROG = 31;
  public static final int OP_ASIGN = 8;
  public static final int COND_MAYORI = 20;
  public static final int OP_DIV = 12;
  public static final int TOK_DOSP = 41;
  public static final int TYPE_STR = 44;
  public static final int OP_PROD = 11;
  public static final int CTE_BIN = 4;
  public static final int ABRIR_PROG = 30;
  public static final int TYPE_INT = 42;
  public static final int ABRIR_LISTA = 33;
  public static final int ABRIR_DECLA = 28;
  public static final int COND_MENOR = 19;
  public static final int ID = 2;
  public static final int TOK_SEP = 40;
  public static final int ABRIR_BLOQUE = 37;
  public static final int DECL_ELSE = 25;
  public static final int COND_DIST = 17;
  public static final int EOF = 0;
  public static final int RETURN = 27;
  public static final int error = 1;
  public static final int COND_MAYOR = 18;
  public static final int OP_OR = 14;
  public static final int OP_RESTA = 10;
  public static final int CERRAR_COND = 36;
  public static final int TYPE_FLOAT = 43;
  public static final int COND_MENORI = 21;
  public static final int ABRIR_COND = 35;
  public static final int DECL_ELIF = 24;
  public static final int CTE_REAL = 5;
  public static final int CTE_INT = 3;
  public static final int OP_DECLA = 7;
  public static final int OP_SUMA = 9;
  public static final int TOK_EOI = 39;
  public static final int CERRAR_LISTA = 34;
  public static final int CERRAR_DECLA = 29;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "ID",
  "CTE_INT",
  "CTE_BIN",
  "CTE_REAL",
  "CTE_STRING",
  "OP_DECLA",
  "OP_ASIGN",
  "OP_SUMA",
  "OP_RESTA",
  "OP_PROD",
  "OP_DIV",
  "OP_AND",
  "OP_OR",
  "OP_NOT",
  "COND_IGUAL",
  "COND_DIST",
  "COND_MAYOR",
  "COND_MENOR",
  "COND_MAYORI",
  "COND_MENORI",
  "CL_WHILE",
  "DECL_IF",
  "DECL_ELIF",
  "DECL_ELSE",
  "OUTPUT",
  "RETURN",
  "ABRIR_DECLA",
  "CERRAR_DECLA",
  "ABRIR_PROG",
  "CERRAR_PROG",
  "FUNC_COUNTDISTINCT",
  "ABRIR_LISTA",
  "CERRAR_LISTA",
  "ABRIR_COND",
  "CERRAR_COND",
  "ABRIR_BLOQUE",
  "CERRAR_BLOQUE",
  "TOK_EOI",
  "TOK_SEP",
  "TOK_DOSP",
  "TYPE_INT",
  "TYPE_FLOAT",
  "TYPE_STR"
  };
}

